### ISSUE TITLE
the :include_blank option for form helper is not working

### ISSUE THREAD

**Issue by rainchen** [jeffp/enumerated_attribute#1]
The option :include_blank is not wokring when set to false
<%= form.enum_select :gender, :include_blank => false %>

The bug is in the rails_helper:
                def to_enum_select_tag(options, html_options={})
                    choices = []
                    if self.object.respond_to?(:enums)
                        enums = self.object.enums(method_name.to_sym)
                        choices = enums ? enums.select_options : []
                        if (value = self.object.**send**(method_name.to_sym))
                            options[:selected] ||= value.to_s
                        else
                            options[:include_blank] ||= true
                        end
                    end
                    to_select_tag(choices, options, html_options)
                end

the line
options[:include_blank] ||= true 
should be
 options[:include_blank] = enums.allows_nil? if options[:include_blank].nil?

**Comment by jeffp** [comment]
Added and submitted --> will be in 0.2.5.
