### ISSUE TITLE
How can i retrierve label text for my enum attribute?

### ISSUE THREAD

**Issue by tanraya** [jeffp/enumerated_attribute#11]
<pre>class Review < ActiveRecord::Base
  STATUS   = [:published, :unpublished, :rejected]

  enum_attr :status, STATUS, :init => :unpublished do
    label :unpublished => 'Not published yet'
    label :published   => 'Published'
    label :rejected    => 'Rejected!'
  end
end

review = Review.new
review.status = :published
</pre>

So, how can i retrieve label text for status attr?
(I'm new to ruby & ror).

**Comment by lailsonbm** [comment]
You can retrieve attribute metadata calling the method `enums` in a given instance and passing the attribute to it. For example:

```
review = Review.new
status = review.enums(:status)
status.class # => EnumeratedAttribute::Attribute::AttributeDescriptor
```

The `AttributeDescriptor` has 3 methods that might interest to you:

```
status.label(:unpublished) # => 'Not published yet'
status.labels # => ['Not published yet', 'Published', 'Rejected!']
status.select_options # => [['Not published yet', 'unpublished], [...
```

I think it's that. Please close this issue if your question was answered.

**Comment by tanraya** [comment]
Thanks lailsonbm, that's is!

**Comment by tanraya** [comment]
closed
