### ISSUE TITLE
Rails 3.0.0 Crash

### ISSUE THREAD

**Issue by thomashs-zz** [jeffp/enumerated_attribute#14]
Hi all. I've intalled enumerated_attribute gem, and my app was working fine with migrations without 't.enum' types. Just rake db:migrate was making some noise for not knowing 'enum' methods.
After putting the line 'config.gem "enumerated_attribute"' in my environment.rb all my rails instance crashed ActiveRecord. Now my app can't connect with database.

I made a test, by installing a new fresh rails instance and creating a simple person scaffold. It works fine, my rails environment is updated and cleanup. But after writing the line to call the gem of 'enumerated_attribute' on my environment.rb, boom!

Any suggestions?

**Comment by exceed** [comment]
The recommended way to manage gems on Rails 3 is to use the Gemfile and bundler Thomas. HTH - Cheers.

**Comment by thomashs-zz** [comment]
Yeah. Since I'm migrating from rails 2.3 and learning, I didn't know how to correctly install a gem. Thanks for feedback! Great work, I'm using enumerated_attribute on a project!
