### ISSUE TITLE
Unnecessary uppercase in view

### ISSUE THREAD

**Issue by woto** [jeffp/enumerated_attribute#16]
Sorry for bad English.
There are unnecessary uppercase in view, may be more better if user could told wich string function he want to use?
According to naming convention i want to use utf8, cp1251 etc. in view, but not Utf8, Cp1251.

By the way thank you for good work!

**Comment by turadg** [comment]
Can you clarify what you're asking for? What is the problem?

**Comment by woto** [comment]
Ok this is real example i got

in model:
enum_attr :encoding_in, [
 'CP1251',
 'CP1252',
 'KOI8-R',
 'CP866',
 'UTF-8',
 'UTF-16LE',
 'UCS-2LE',
 'AUTO'
], :nil => true

in view:
<%= f.enum_select :encoding_in %>

Cp1251
Cp1252
Koi8-r

cp1251 != CP1251 != Cp1251
