### ISSUE TITLE
Easier way to get label

### ISSUE THREAD

**Issue by timster** [jeffp/enumerated_attribute#25]
This is more of a question than an issue. I'm just wondering if there is a more convenient way of getting the label for an enum?

Lets say I have an enum_attr called "visibility" on the Post model. Right now I'm doing this:

p = Post.find(1)
p.enums(:visibility).label(p.visibility)

Is there an easier way?

**Comment by tinynumbers** [comment]
``` ruby
p.visibilities.label(p.visibility)
```

 (...though I don't know that this is any better.)

#47 also discusses the difficulty of getting the label for an enumeration value.
