### ISSUE TITLE
Cannot use accentued character.

### ISSUE THREAD

**Issue by sylario** [jeffp/enumerated_attribute#28]
Accentued special char ( éèàÉÈã....) cannot be used as enum value. Problematic in almost all non english-germanic language.

**Comment by turadg** [comment]
Can't you just put those values on the labels? Enum _values_ are for the db, not the user.

**Comment by sylario** [comment]
How do you display a label? stuff.enumtype.label does not work

**Comment by turadg** [comment]
That's documented in the README and also answered in #11.
