### ISSUE TITLE
formtastic support

### ISSUE THREAD

**Issue by anshul** [jeffp/enumerated_attribute#4]
How do I display the select input in a formtastic form?

**Comment by britto** [comment]
I had to do a little monkey patching to accomplish this.

First, extend formtastic with an initializer:

<pre>
require 'formtastic'

module Formtastic #:nodoc:
  class SemanticFormBuilder #:nodoc:
    def enum_input(method, options)
      unless options[:collection]
        enum = @object.enums(method.to_sym)
        choices = enum ? enum.select_options : []
        options[:collection] = choices
      end
      if (value = @object.__send__(method.to_sym))
        options[:selected] ||= value.to_s
      else
        options[:include_blank] ||= true
      end
      select_input(method, options)
    end
  end
end
</pre>


Then specify the input type as enum in the forms:

<pre>form.input :gear, :as => :enum</pre>


Reflection on column type would be a great addition, so :as => :enum would not be required provided the :gears column is migrated as t.enum

**Comment by sftsang** [comment]
Thanks for this... it was exactly what I was looking for. It doesn't seem to automagically change the select field to whatever was inputted into the database however. Is there something extra that needs to be done?

**Comment by sftsang** [comment]
Never mind the above. Just make sure that when defining the enum options in your model to have the same case as is defined in the actual database ;)

**Comment by turadg** [comment]
Copied this into README.rdoc
