### ISSUE TITLE
Assigning non-enum attributes under inheritance throws error Rails 2.3.5

### ISSUE THREAD

**Issue by rchekaluk** [jeffp/enumerated_attribute#6]
Model app/models/parent.rb

   require 'enumerated_attribute'
   class Parent < ActiveRecord::Base
     enum_attr :parent_enum, %w(pvaluea pvalueb)
   end

Model app/models/sub.rb

   require 'enumerated_attribute'
   class Sub < Parent
     enum_attr :sub_enum, %w(svalue1 svalue2)
   end

Migration db/migrate/20100518233259_create_parents.rb

   class CreateParents < ActiveRecord::Migration
     def self.up
       create_table :parents do |t|
         t.string :type
         t.string :parent_enum
         t.timestamps
       end
     end
     def self.down
       drop_table :parents
     end
   end

Migration db/migrate/20100518233302_add_sub_to_parents.rb

   class AddSubToParents < ActiveRecord::Migration
     def self.up
       add_column :parents, :sub_nonenum, :string
       add_column :parents, :sub_enum, :string
     end
     def self.down
       remove_column :parents, :sub_enum
       remove_column :parents, :sub_nonenum
     end
   end

Unit test sub_test.rb

   require File.dirname(**FILE**) + '/../test_helper'
   class SubTest < ActiveSupport::TestCase
     test "enums for parent_enum" do
       s = Sub.new()
       s.parent_enum = :pvaluea
       assert s.parent_enum == :pvaluea
       begin
         s.parent_enum = :bleech
       rescue
       end
       assert s.parent_enum == :pvaluea
       s.sub_nonenum = "any assignment causes error"
     end
     test "enums for sub_enum" do
       s = Sub.new()
       s.sub_enum = :svalue2
       assert s.sub_enum == :svalue2
       begin
         s.sub_enum = :bleech
       rescue
       end
       assert s.sub_enum == :svalue2
       s.sub_nonenum = "any assignment causes error"
     end
   end

Unit test output

  /usr/bin/ruby -I"lib:test" "/usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb" "test/unit/helpers/subs_helper_test.rb" "test/unit/sub_test.rb" "test/unit/parent_test.rb" 
  (in /home/xyz/abc/simple)
  Loaded suite /usr/lib64/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader
  Started
  .EE.
  Finished in 0.21079 seconds.

  1) Error:
test_enums_for_parent_enum(SubTest):
SystemStackError: stack level too deep
    (eval):78:in `define_enumerated_attribute_dynamic_method'
    (eval):5:in`method_missing_without_enumerated_attribute'
    (eval):6:in `method_missing_without_enumerated_attribute'
    (eval):6:in`method_missing'
    /test/unit/sub_test.rb:15:in `test_enums_for_parent_enum'

  2) Error:
test_enums_for_sub_enum(SubTest):
SystemStackError: stack level too deep
    (eval):5:in `method_missing_without_enumerated_attribute'
    (eval):6:in`method_missing_without_enumerated_attribute'
    (eval):6:in `method_missing'
    /test/unit/sub_test.rb:29:in`test_enums_for_sub_enum'

  4 tests, 6 assertions, 0 failures, 2 errors
  rake aborted!
  Command failed with status (1): [/usr/bin/ruby -I"lib:test" "/usr/lib64/rub...]

  (See full trace by running task with --trace)

**Comment by jeffp** [comment]
Thanks, Rob, for your report and the accompanying spec tests.  The problem you observed regarded circular references for respond_to? and method_missing methods when enum_attr was used for STI active record classes.  STIs had not been tested and your submission has been added to the tests and fixes have been submitted.  Version 0.2.4 on rubygems.org is ready to go.
