### ISSUE TITLE
dry_scaffold sometimes crashes when used with this plugin

### ISSUE THREAD

**Issue by anshul** [jeffp/enumerated_attribute#7]
Ruby 1.9.1, latest dry_scaffold and enumerated_attribute sometimes crashes with the error

```
/usr/lib64/ruby/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require': no such file to load -- rails/generators (MissingSourceFile)
from /usr/lib64/ruby/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `block in require'
from /usr/lib64/ruby/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
from /usr/lib64/ruby/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
from /home/anshul/project/vendor/plugins/enumerated_attribute/lib/enumerated_attribute/rails_helpers.rb:28:in `<top (required)>'
```

This happens because rescue on that line 30 is ineffective.  Here is a trivial patch... http://baboonlogic.com/files/0001-BUGFIX-incorrect-use-of-rescue.patch

**Comment by jeffp** [comment]
anshul - thanks for submitting the fix.  are you proposing the following

```
begin
  ...

rescue
rescue Exception => ex
end
```

?

Thanks,
J

**Comment by anshul** [comment]
Keeping or deleting the first rescue should not make a difference.  I wanted to keep the patch minimal so I left it there.   Thanks for applying the patch.
