### ISSUE TITLE
Rails 3 error

### ISSUE THREAD

**Issue by mysticflute** [jeffp/enumerated_attribute#8]
I added a basic enum field, then when running db:migrate it complains about this:
undefined method `to_tag' for class`ActionView::Helpers::InstanceTag'

**Comment by mysticflute** [comment]
well, I apologize for filing this if this is my mistake, but it looks like the changes to make this work with rails 3 are there. installing the gem seems to install the old version, though, which must be why i still get the error.

**Comment by jeffp** [comment]
I thought the changes were there.  Perhaps I need to update the gem.  Thanks for the info.

**Comment by MSch** [comment]
Yes, please push 0.2.14 to rubygems.org

**Comment by jeffp** [comment]
MSch - thanks for the reminder.  0.2.16 pushed.
